import { Doctor } from './types';

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Sarah Jenkins, MD',
    title: 'Board-Certified Adult Psychiatrist',
    email: 'sarah.jenkins@healconnect.med',
    phone: '+1 (555) 234-8901',
    bio: 'Dr. Jenkins specializes in mood disorders, treatment-resistant depression, and adult ADHD. With over 14 years of clinical practice, she combines evidence-based psychopharmacology with supportive cognitive behavioral strategies.',
    specializations: ['Depression', 'Anxiety & Panic', 'Adult ADHD', 'Bipolar Disorder'],
    experience: 14,
    education: 'Johns Hopkins University School of Medicine (MD), Columbia Psychiatry Residency',
    hospitalAffiliation: 'Metropolitan Health Center',
    location: 'New York, NY (In-Person & Telehealth)',
    consultationFee: 180,
    currency: 'USD',
    availableDays: ['Monday', 'Tuesday', 'Thursday'],
    availableHours: '9:00 AM - 4:30 PM EST',
    consultationModes: ['Phone Call', 'Video Consultation', 'In-Person'],
    languages: ['English', 'Spanish'],
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&auto=format&fit=crop&q=80',
    rating: 4.95,
    reviewCount: 48,
    isVerified: true,
    isActive: true,
    isFeatured: true,
    createdAt: new Date('2024-01-10').toISOString(),
    updatedAt: new Date('2024-01-10').toISOString(),
  },
  {
    id: 'doc-2',
    name: 'Dr. Marcus Vance, MD, PhD',
    title: 'Neuropsychiatrist & Sleep Medicine Specialist',
    email: 'm.vance@healconnect.med',
    phone: '+1 (555) 345-6789',
    bio: 'Dr. Vance focuses on the intersection of neurological wellness, insomnia, and trauma-related stress. He takes a holistic, biological, and compassionate approach to mental clarity and emotional regulation.',
    specializations: ['PTSD & Trauma', 'Sleep & Insomnia', 'Stress Management', 'Anxiety'],
    experience: 18,
    education: 'Stanford University School of Medicine (MD/PhD), UCSF Fellow',
    hospitalAffiliation: 'Pacific Neuroscience Institute',
    location: 'San Francisco, CA (Telehealth available nationwide)',
    consultationFee: 220,
    currency: 'USD',
    availableDays: ['Tuesday', 'Wednesday', 'Friday', 'Saturday'],
    availableHours: '10:00 AM - 6:00 PM PST',
    consultationModes: ['Video Consultation', 'Phone Call'],
    languages: ['English'],
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 36,
    isVerified: true,
    isActive: true,
    isFeatured: true,
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'doc-3',
    name: 'Dr. Elena Rostova, MD',
    title: 'Child & Adolescent Psychiatrist',
    email: 'elena.rostova@healconnect.med',
    phone: '+1 (555) 456-7890',
    bio: 'Dedicated to helping young people and families navigate behavioral challenges, developmental conditions, school anxiety, and emotional resilience with empathetic, family-centered care.',
    specializations: ['Child & Adolescent', 'Autism Spectrum Support', 'Social Anxiety', 'ADHD'],
    experience: 11,
    education: 'Yale School of Medicine (MD), Boston Children’s Hospital Fellowship',
    hospitalAffiliation: 'Northwestern Memorial Care',
    location: 'Chicago, IL (In-Person & Telehealth)',
    consultationFee: 160,
    currency: 'USD',
    availableDays: ['Monday', 'Wednesday', 'Friday'],
    availableHours: '1:00 PM - 7:00 PM CST',
    consultationModes: ['Video Consultation', 'Phone Call', 'In-Person'],
    languages: ['English', 'Russian'],
    image: 'https://images.unsplash.com/photo-1594824813533-46953a0058b2?w=500&auto=format&fit=crop&q=80',
    rating: 4.88,
    reviewCount: 29,
    isVerified: true,
    isActive: true,
    isFeatured: true,
    createdAt: new Date('2024-02-01').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: 'doc-4',
    name: 'Dr. Dawit Abebe, MD',
    title: 'Consultant Psychiatrist & Addiction Medicine',
    email: 'dawit.abebe@healconnect.med',
    phone: '+1 (555) 567-8901',
    bio: 'Dr. Abebe provides compassionate psychiatric evaluations and evidence-based addiction recovery consultations, dual diagnosis treatment, and grief counseling tailored to cultural contexts.',
    specializations: ['Addiction Recovery', 'Dual Diagnosis', 'Grief & Loss', 'Depression'],
    experience: 16,
    education: 'Addis Ababa University (MD), University of Washington Psychiatry Residency',
    hospitalAffiliation: 'Evergreen Health Alliance',
    location: 'Seattle, WA (Telehealth & Hybrid)',
    consultationFee: 150,
    currency: 'USD',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
    availableHours: '8:00 AM - 3:30 PM PST',
    consultationModes: ['Phone Call', 'Video Consultation'],
    languages: ['English', 'Amharic'],
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=500&auto=format&fit=crop&q=80',
    rating: 4.96,
    reviewCount: 52,
    isVerified: true,
    isActive: true,
    isFeatured: true,
    createdAt: new Date('2024-02-10').toISOString(),
    updatedAt: new Date('2024-02-10').toISOString(),
  },
  {
    id: 'doc-5',
    name: 'Dr. Priya Patel, MD',
    title: 'Perinatal & Women’s Mental Health Psychiatrist',
    email: 'priya.patel@healconnect.med',
    phone: '+1 (555) 678-9012',
    bio: 'Specializing in reproductive psychiatry, postpartum depression, hormonal mood changes, and life transition anxieties. Dedicated to creating a safe, non-judgmental space for women.',
    specializations: ['Perinatal & Postpartum', 'Women’s Mental Health', 'Anxiety & Panic', 'Burnout'],
    experience: 9,
    education: 'University of Pennsylvania Perelman School of Medicine (MD)',
    hospitalAffiliation: 'Cedar Sinai Women’s Pavilion',
    location: 'Los Angeles, CA (Telehealth available)',
    consultationFee: 175,
    currency: 'USD',
    availableDays: ['Tuesday', 'Thursday', 'Saturday'],
    availableHours: '9:30 AM - 5:00 PM PST',
    consultationModes: ['Video Consultation', 'Phone Call'],
    languages: ['English', 'Hindi', 'Gujarati'],
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&auto=format&fit=crop&q=80',
    rating: 4.92,
    reviewCount: 31,
    isVerified: true,
    isActive: true,
    isFeatured: false,
    createdAt: new Date('2024-02-20').toISOString(),
    updatedAt: new Date('2024-02-20').toISOString(),
  },
  {
    id: 'doc-6',
    name: 'Dr. Robert Chen, MD',
    title: 'Geriatric & Integrative Psychiatrist',
    email: 'robert.chen@healconnect.med',
    phone: '+1 (555) 789-0123',
    bio: 'Specializing in cognitive health in aging, memory disorders, late-life depression, and integrative lifestyle psychiatry for longevity and cognitive wellness.',
    specializations: ['Geriatric Psychiatry', 'Memory & Cognitive Health', 'Depression', 'Chronic Illness Support'],
    experience: 22,
    education: 'Harvard Medical School (MD), Brigham and Women’s Hospital Fellow',
    hospitalAffiliation: 'Mass General Brigham',
    location: 'Boston, MA (In-Person & Telehealth)',
    consultationFee: 195,
    currency: 'USD',
    availableDays: ['Monday', 'Tuesday', 'Wednesday'],
    availableHours: '10:00 AM - 4:00 PM EST',
    consultationModes: ['Phone Call', 'Video Consultation', 'In-Person'],
    languages: ['English', 'Mandarin'],
    image: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=500&auto=format&fit=crop&q=80',
    rating: 4.98,
    reviewCount: 64,
    isVerified: true,
    isActive: true,
    isFeatured: false,
    createdAt: new Date('2024-03-01').toISOString(),
    updatedAt: new Date('2024-03-01').toISOString(),
  },
  {
    id: 'doc-7',
    name: 'Dr. Amina Touré, MD',
    title: 'Consultant Psychiatrist & Psychotherapist',
    email: 'amina.toure@healconnect.med',
    phone: '+1 (555) 890-1234',
    bio: 'Dr. Touré specializes in relationship dynamics, existential anxiety, cultural adaptation stress, and bipolar spectrum conditions with an integrative mind-body framework.',
    specializations: ['Bipolar Disorder', 'Relationship & Identity', 'Stress Management', 'Depression'],
    experience: 12,
    education: 'McGill University Faculty of Medicine (MD), NYU Langone Residency',
    hospitalAffiliation: 'Austin Integrated Health',
    location: 'Austin, TX (Telehealth available)',
    consultationFee: 165,
    currency: 'USD',
    availableDays: ['Wednesday', 'Thursday', 'Friday'],
    availableHours: '11:00 AM - 7:00 PM CST',
    consultationModes: ['Video Consultation', 'Phone Call'],
    languages: ['English', 'French'],
    image: 'https://images.unsplash.com/photo-1594824813533-46953a0058b2?w=500&auto=format&fit=crop&q=80',
    rating: 4.89,
    reviewCount: 22,
    isVerified: true,
    isActive: true,
    isFeatured: false,
    createdAt: new Date('2024-03-15').toISOString(),
    updatedAt: new Date('2024-03-15').toISOString(),
  }
];

export const SPECIALIZATIONS_LIST = [
  'All Specializations',
  'Depression',
  'Anxiety & Panic',
  'Adult ADHD',
  'Child & Adolescent',
  'PTSD & Trauma',
  'Bipolar Disorder',
  'Sleep & Insomnia',
  'Addiction Recovery',
  'Perinatal & Postpartum',
  'Women’s Mental Health',
  'Geriatric Psychiatry',
  'Stress Management',
  'Grief & Loss',
];

export const CONSULTATION_MODES = [
  'All Modes',
  'Phone Call',
  'Video Consultation',
  'In-Person'
];
