import { Doctor } from './types';

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Sarah Jenkins, MD',
    title: 'Board-Certified Adult Psychiatrist',
    email: 'sarah.jenkins@healconnect.med',
    phone: '+1 (212) 843-8901',
    bio: 'Dr. Jenkins specializes in mood disorders, treatment-resistant depression, and adult ADHD. With over 14 years of clinical practice, she combines evidence-based psychopharmacology with supportive cognitive behavioral strategies.',
    specializations: ['Depression', 'Anxiety & Panic', 'Adult ADHD', 'Bipolar Disorder'],
    experience: 14,
    education: 'Johns Hopkins University School of Medicine (MD), Columbia Psychiatry Residency',
    hospitalAffiliation: 'Metropolitan Health Center',
    location: 'New York, NY (In-Person & Telehealth)',
    consultationFee: 180,
    currency: 'USD',
    availableDays: ['Monday', 'Tuesday', 'Thursday'],
    availableHours: '9:00 AM - 4:30 PM EST',
    consultationModes: ['Phone Call', 'Video Consultation', 'In-Person'],
    languages: ['English', 'Spanish'],
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&auto=format&fit=crop&q=80',
    rating: 4.95,
    reviewCount: 48,
    isVerified: true,
    isActive: true,
    isFeatured: true,
    createdAt: new Date('2024-01-10').toISOString(),
    updatedAt: new Date('2024-01-10').toISOString(),
  },
  {
    id: 'doc-2',
    name: 'Dr. Dawit Abebe, MD',
    title: 'Consultant Psychiatrist & Addiction Medicine',
    email: 'dawit.abebe@healconnect.med',
    phone: '+251 91 142 8901',
    bio: 'Dr. Abebe provides compassionate psychiatric evaluations, dual diagnosis care, and anxiety treatment tailored to cultural contexts with 16 years of distinguished clinical experience in Addis Ababa.',
    specializations: ['Addiction Recovery', 'Dual Diagnosis', 'Grief & Loss', 'Depression'],
    experience: 16,
    education: 'Addis Ababa University (MD), University of Washington Psychiatry Residency',
    hospitalAffiliation: 'St. Paul Hospital Millennium Medical College',
    location: 'Addis Ababa, Ethiopia (In-Person & Telehealth)',
    consultationFee: 2800,
    currency: 'ETB',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
    availableHours: '8:30 AM - 4:30 PM EAT',
    consultationModes: ['Phone Call', 'Video Consultation', 'In-Person'],
    languages: ['Amharic', 'English'],
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=500&auto=format&fit=crop&q=80',
    rating: 4.96,
    reviewCount: 52,
    isVerified: true,
    isActive: true,
    isFeatured: true,
    createdAt: new Date('2024-02-10').toISOString(),
    updatedAt: new Date('2024-02-10').toISOString(),
  },
  {
    id: 'doc-3',
    name: 'Dr. Marcus Vance, MD, PhD',
    title: 'Neuropsychiatrist & Sleep Medicine Specialist',
    email: 'm.vance@healconnect.med',
    phone: '+1 (415) 629-6789',
    bio: 'Dr. Vance focuses on the intersection of neurological wellness, insomnia, and trauma-related stress. He takes a holistic, biological, and compassionate approach to mental clarity and emotional regulation.',
    specializations: ['PTSD & Trauma', 'Sleep & Insomnia', 'Stress Management', 'Anxiety & Panic'],
    experience: 18,
    education: 'Stanford University School of Medicine (MD/PhD), UCSF Fellow',
    hospitalAffiliation: 'Pacific Neuroscience Institute',
    location: 'San Francisco, CA (Telehealth available nationwide)',
    consultationFee: 220,
    currency: 'USD',
    availableDays: ['Tuesday', 'Wednesday', 'Friday', 'Saturday'],
    availableHours: '10:00 AM - 6:00 PM PST',
    consultationModes: ['Video Consultation', 'Phone Call'],
    languages: ['English'],
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 36,
    isVerified: true,
    isActive: true,
    isFeatured: true,
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'doc-4',
    name: 'Dr. Bethlehem Mengistu, MD',
    title: 'Child, Adolescent & Perinatal Psychiatrist',
    email: 'bethlehem.mengistu@healconnect.med',
    phone: '+251 92 388 9012',
    bio: 'Dedicated to helping children, mothers, and families navigate emotional wellness, postpartum depression, ADHD, and school stress in a warm, patient-first clinical environment.',
    specializations: ['Child & Adolescent', 'Perinatal & Postpartum', 'Adult ADHD', 'Anxiety & Panic'],
    experience: 11,
    education: 'Tikur Anbessa Specialized Hospital (MD), Toronto Child Psychiatry Fellowship',
    hospitalAffiliation: 'Addis Care Specialty Clinic',
    location: 'Addis Ababa, Ethiopia (In-Person & Telehealth)',
    consultationFee: 2500,
    currency: 'ETB',
    availableDays: ['Tuesday', 'Thursday', 'Saturday'],
    availableHours: '9:00 AM - 5:00 PM EAT',
    consultationModes: ['Video Consultation', 'Phone Call', 'In-Person'],
    languages: ['Amharic', 'English'],
    image: 'https://images.unsplash.com/photo-1594824813533-46953a0058b2?w=500&auto=format&fit=crop&q=80',
    rating: 4.93,
    reviewCount: 41,
    isVerified: true,
    isActive: true,
    isFeatured: true,
    createdAt: new Date('2024-02-01').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: 'doc-5',
    name: 'Dr. Elena Rostova, MD',
    title: 'Child & Adolescent Psychiatrist',
    email: 'elena.rostova@healconnect.med',
    phone: '+1 (312) 754-4567',
    bio: 'Dedicated to helping young people and families navigate behavioral challenges, developmental conditions, school anxiety, and emotional resilience with empathetic, family-centered care.',
    specializations: ['Child & Adolescent', 'Autism Spectrum Support', 'Social Anxiety', 'Adult ADHD'],
    experience: 11,
    education: 'Yale School of Medicine (MD), Boston Children’s Hospital Fellowship',
    hospitalAffiliation: 'Northwestern Memorial Care',
    location: 'Chicago, IL (In-Person & Telehealth)',
    consultationFee: 160,
    currency: 'USD',
    availableDays: ['Monday', 'Wednesday', 'Friday'],
    availableHours: '1:00 PM - 7:00 PM CST',
    consultationModes: ['Video Consultation', 'Phone Call', 'In-Person'],
    languages: ['English', 'Russian'],
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&auto=format&fit=crop&q=80',
    rating: 4.88,
    reviewCount: 29,
    isVerified: true,
    isActive: true,
    isFeatured: false,
    createdAt: new Date('2024-02-01').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: 'doc-6',
    name: 'Dr. Robert Chen, MD',
    title: 'Geriatric & Integrative Psychiatrist',
    email: 'robert.chen@healconnect.med',
    phone: '+1 (617) 492-0123',
    bio: 'Specializing in cognitive health in aging, memory disorders, late-life depression, and integrative lifestyle psychiatry for longevity and cognitive wellness.',
    specializations: ['Geriatric Psychiatry', 'Memory & Cognitive Health', 'Depression', 'Stress Management'],
    experience: 22,
    education: 'Harvard Medical School (MD), Brigham and Women’s Hospital Fellow',
    hospitalAffiliation: 'Mass General Brigham',
    location: 'Boston, MA (In-Person & Telehealth)',
    consultationFee: 195,
    currency: 'USD',
    availableDays: ['Monday', 'Tuesday', 'Wednesday'],
    availableHours: '10:00 AM - 4:00 PM EST',
    consultationModes: ['Phone Call', 'Video Consultation', 'In-Person'],
    languages: ['English', 'Mandarin'],
    image: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=500&auto=format&fit=crop&q=80',
    rating: 4.98,
    reviewCount: 64,
    isVerified: true,
    isActive: true,
    isFeatured: false,
    createdAt: new Date('2024-03-01').toISOString(),
    updatedAt: new Date('2024-03-01').toISOString(),
  },
  {
    id: 'doc-7',
    name: 'Dr. Yonas Haile, MD',
    title: 'Consultant Neuropsychiatrist & Stress Management',
    email: 'yonas.haile@healconnect.med',
    phone: '+251 93 456 7890',
    bio: 'Dr. Yonas provides comprehensive evaluations for stress-related somatic disorders, sleep disturbances, anxiety, and work-related burnout with evidence-based modern therapeutics.',
    specializations: ['Stress Management', 'Sleep & Insomnia', 'Anxiety & Panic', 'Depression'],
    experience: 13,
    education: 'Gondar College of Medicine (MD), Karolinska Institute Fellow',
    hospitalAffiliation: 'Bethezetha Specialized Medical Center',
    location: 'Addis Ababa, Ethiopia (Telehealth & In-Person)',
    consultationFee: 3200,
    currency: 'ETB',
    availableDays: ['Wednesday', 'Thursday', 'Friday'],
    availableHours: '10:00 AM - 6:00 PM EAT',
    consultationModes: ['Video Consultation', 'Phone Call', 'In-Person'],
    languages: ['Amharic', 'English'],
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=500&auto=format&fit=crop&q=80',
    rating: 4.91,
    reviewCount: 38,
    isVerified: true,
    isActive: true,
    isFeatured: false,
    createdAt: new Date('2024-03-15').toISOString(),
    updatedAt: new Date('2024-03-15').toISOString(),
  }
];

export const SPECIALIZATIONS_LIST = [
  'All Specializations',
  'Depression',
  'Anxiety & Panic',
  'Adult ADHD',
  'Child & Adolescent',
  'PTSD & Trauma',
  'Bipolar Disorder',
  'Sleep & Insomnia',
  'Addiction Recovery',
  'Perinatal & Postpartum',
  'Women’s Mental Health',
  'Geriatric Psychiatry',
  'Stress Management',
  'Grief & Loss',
];

export const CONSULTATION_MODES = [
  'All Modes',
  'Phone Call',
  'Video Consultation',
  'In-Person'
];

export const CURRENCIES_LIST = [
  'All Currencies',
  'ETB',
  'USD'
];
